# Generated by Django 3.0.5 on 2020-06-19 04:01

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('lf_app', '0002_auto_20200619_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
